apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    postgresql-password: AgAOKxZOTZ4gf2r4fbVEWZEUQP0fS+8/5mQ60RjeAa5rGtFvz2NjnoT14O6Uwv/iS3PSbWo7dpLck1JhkMwlfOLbX9fPtbf2yYeKZDBQJ67GsxBBWYzMf7/n9NGNNfIZM5m6dlrf11GSoBU6zMNGMoYLAJSXI+e8H4Rmo8tTqo+rpni3HjAYHUDSxOblqzlEFqqfAGp8xOAGFA0LFYrrxR0n1ov5pRUOScAPlfhG6ebFU3a84WJhXw6tq2I2eps3wedY3N0aevYupyAws/kr9WZNJvSKDZBfxMy5EKG9NkUil5D4UCantqeq7RV2/Nz4roiWszYMC6KDwIqdUNrWblpqrPN32vlPa+N1TbS8caQMEg7t1/fpHQTUW3+gQUzbYhaDLLxONsFxwBxAHyD/5xVJhBx1Bk20HcaYDFVNKSYkn0t+w1Y7RWjzKpYPU9MAA86HGBdb5dj2WZAzXaE51yvsA56nmYE3E7XJPnL/jnIrElPoyX9YHX+enFmLa2QlVhhkp1gUDUxNJTiSNfzyovoQL7iY+1OiqAKC4A/+Gzp082GF0DD4S3O6inX2jfe2oezP9hhbD5/NIKla//M4B2He2Ow6Hpy8Xcj4ptFpxWpSFgYRD1TIitjYY2YA0A6D931JOSFR3MFzy3k9caF+AAPnbrw6Gwm+I3eBAYTXbwQ7O78X6npHHMacTxXdqqmUzqVrQv+NfAY9dWIT
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
            - name: POSTGRES_DB
              value: testdb
            - name: POSTGRES_USER
              value: jian
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgresql-password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
   app: postgres