apiVersion: v1
kind: Service
metadata:
  name: calculate-service
spec:
  type: LoadBalancer
  selector:
    app: calculate-app
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 8080
      targetPort: 8080
